### ISSUE TITLE
小説検索がおかしい

### ISSUE THREAD

**Issue by book000** [tomacheese/my-pixiv#393]
my-pixiv-api-1   | TypeError: result.data.novels is not iterable (cannot read property undefined)
my-pixiv-api-1   |     at SearchNovel.<anonymous> (/app/index.js:881:24)
my-pixiv-api-1   |     at Generator.next (<anonymous>)
my-pixiv-api-1   |     at fulfilled (/app/index.js:800:58)
my-pixiv-api-1   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by book000** [comment]
わからん。rate limitか？
